version: '3.6'

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: mychatdb
      POSTGRES_PASSWORD: mychatdb
      POSTGRES_DB: mychatdb
    command: -c fsync=off
    ports:
        - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
    image: icontext:latest
    entrypoint: gunicorn
    command: --reload --workers=2 --threads=2 --max-requests 1000 --bind 0.0.0.0:8000 icontext.wsgi
    ports:
      - 8000
    volumes:
      - .:/app/icontext
    depends_on:
      - db

  api:
    image: icontext:latest
    environment:
      DJANGO_SETTINGS_MODULE: 'icontext.settings'
    entrypoint: python
    command: aio-server.py
    ports:
      - 8080
    volumes:
      - .:/app/icontext
    depends_on:
      - app
      - db

  proxy:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - app
      - api

volumes:
  pgdata: